import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { NavbarComponent } from '@src/app/navbar/navbar.component';
import { FooterComponent } from '@src/app/footer/footer.component';
import {FormsModule, ReactiveFormsModule} from "@angular/forms";
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { PereComponent } from '@src/app/pere/pere.component';
import { FilsComponent } from '@src/app/pere/fils/fils.component';
import { StudentComponent } from '@src/app/student/student.component';
import { AddComponent } from '@src/app/add/add.component';
import {HttpClientModule} from "@angular/common/http";

@NgModule({
  declarations: [
    AppComponent,
    NavbarComponent,
    FooterComponent,
    AutoGeneratedComponent,
    PereComponent,
    FilsComponent,
    StudentComponent,
    AddComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    FormsModule,
    ReactiveFormsModule,
    HttpClientModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
